import { createClient } from "@supabase/supabase-js";
import { createIcons, ArrowLeft, ArrowRight, UserRound, Mail, LockKeyhole, ShieldCheck, EyeOff, Eye } from "lucide";
const supabaseUrl=import.meta.env.VITE_SUPABASE_URL; const supabaseKey=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
if(!supabaseUrl||!supabaseKey){document.body.innerHTML='<div style="font-family:system-ui;padding:30px;max-width:700px;margin:auto"><h2>Supabase configuration missing</h2><p>Create a <code>.env</code> file from <code>.env.example</code>, add your Supabase URL and publishable key, then restart Vite.</p></div>';throw new Error("Missing Supabase environment variables")}
const supabase=createClient(supabaseUrl,supabaseKey); const $=id=>document.getElementById(id); let mode=new URLSearchParams(location.search).get("mode")==="signup"?"signup":"login";
function icons(){createIcons({icons:{ArrowLeft,ArrowRight,UserRound,Mail,LockKeyhole,ShieldCheck,EyeOff,Eye}})}
function setMode(next){mode=next;document.querySelectorAll(".signup-only").forEach(el=>el.classList.toggle("hidden",mode!=="signup"));$("formTitle").textContent=mode==="signup"?"Create your Prepvia account":"Sign in to Prepvia";$("formSubtitle").textContent=mode==="signup"?"Create your account and start your preparation.":"Continue your preparation from where you left off.";$("modeEyebrow").textContent=mode==="signup"?"GET STARTED":"WELCOME BACK";$("headingIcon").textContent=mode==="signup"?"🚀":"👋";$("submitText").textContent=mode==="signup"?"Create account":"Sign in";$("googleText").textContent=mode==="signup"?"Sign up with Google":"Continue with Google";$("switchMode").innerHTML=mode==="signup"?`Already have an account? <button type="button">Sign in</button>`:`Don't have an account? <button type="button">Create account</button>`;$("switchMode").querySelector("button").onclick=()=>setMode(mode==="signup"?"login":"signup");$("password").autocomplete=mode==="signup"?"new-password":"current-password";$("forgotLink").style.visibility=mode==="signup"?"hidden":"visible";$("strength").classList.toggle("hidden",mode!=="signup");history.replaceState(null,"",mode==="signup"?"/auth.html?mode=signup":"/auth.html");clearMessage();icons()}
function showMessage(text,type="error"){const box=$("message");box.textContent=text;box.className=`message ${type}`} function clearMessage(){$("message").textContent="";$ ("message").className="message"}
function setLoading(loading,label){$("submitButton").disabled=loading;$("googleButton").disabled=loading;$("submitText").textContent=loading?label:(mode==="signup"?"Create account":"Sign in");$("spinner").classList.toggle("hidden",!loading)}
$("authForm").addEventListener("submit",async e=>{e.preventDefault();clearMessage();const email=$("email").value.trim().toLowerCase(),password=$("password").value;if(!email||!email.includes("@"))return showMessage("Please enter a valid email address.");if(password.length<8)return showMessage("Password must contain at least 8 characters.");if(mode==="signup"){const fullName=$("fullName").value.trim(),confirm=$("confirmPassword").value;if(fullName.length<2)return showMessage("Please enter your full name.");if(password!==confirm)return showMessage("Passwords do not match.");if(!$("terms").checked)return showMessage("Please accept the Terms of Use and Privacy Policy.");setLoading(true,"Creating account…");const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName,exam:document.querySelector('input[name="exam"]:checked')?.value||"JEE"},emailRedirectTo:`${location.origin}/dashboard.html`}});setLoading(false);if(error)return showMessage(error.message);if(data.session)location.href="/dashboard.html";else{showMessage("Account created! Check your email to verify your account before signing in.","success");$("authForm").reset()}}else{setLoading(true,"Signing in…");const {data,error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error)return showMessage("Unable to sign in. Please check your email and password.");if(data.session)location.href="/dashboard.html"}});
$("googleButton").addEventListener("click",async()=>{clearMessage();$("googleButton").disabled=true;const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/dashboard.html`}});if(error){$("googleButton").disabled=false;showMessage(error.message)}});
$("forgotLink").addEventListener("click",async e=>{e.preventDefault();const email=$("email").value.trim().toLowerCase();if(!email||!email.includes("@"))return showMessage("Enter your email address first.");const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/reset.html`});if(error)return showMessage(error.message);showMessage("If an account exists for this email, a password-reset link has been sent.","success")});
$("togglePassword").addEventListener("click",()=>{const input=$("password"),showing=input.type==="text";input.type=showing?"password":"text";$("togglePassword").innerHTML=`<i data-lucide="${showing?"eye-off":"eye"}"></i>`;icons()});
$("password").addEventListener("input",()=>{if(mode!=="signup")return;const p=$("password").value,score=[p.length>=8,/[A-Z]/.test(p),/[0-9]/.test(p),/[^A-Za-z0-9]/.test(p)].filter(Boolean).length;document.querySelectorAll(".strength span").forEach((s,i)=>s.classList.toggle("on",i<score));$("strength").querySelector("small").textContent=score<2?"Weak password":score<4?"Good password":"Strong password"});
supabase.auth.getSession().then(({data})=>{if(data.session)location.href="/dashboard.html"});setMode(mode);icons();
